apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/ignore: "false"
  name: flux
  namespace: flux
spec:
  chart:
    name: helm-operator
    repository: https://charts.fluxcd.io/
    version: 1.0.2
  releaseName: helm-operator
  values:
    createCRD: false
    git:
      ssh:
        secretName: flux-git-deploy
    helm:
      versions: v3
    prometheus:
      enabled: true
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 64Mi
      serviceMonitor:
        create: true
        interval: 30s
        namespace: flux
        scrapeTimeout: 10s
