apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: pihole
  name: pihole
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-etc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-dnsmasq
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Lisbon
          image: pihole/pihole:beta-v5.0
          imagePullPolicy: IfNotPresent
          name: pihole
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-pvc-etc
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-pvc-dnsmasq
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: pihole
  name: pihole-tcp
  namespace: pihole
spec:
  loadBalancerIP: 192.168.1.230
  ports:
    - name: pihole-tcp-80
      port: 80
      protocol: TCP
      targetPort: 80
    - name: pihole-tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: pihole
  name: pihole-udp
  namespace: pihole
spec:
  loadBalancerIP: 192.168.1.230
  ports:
    - name: pihole-udp-80
      port: 80
      protocol: UDP
      targetPort: 80
    - name: pihole-udp-53
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: pihole
  type: LoadBalancer
