apiVersion: v1
kind: Namespace
metadata:
  name: unifi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: unifi
spec:
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Lisbon
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
          image: linuxserver/unifi-controller:5.12.66-ls57
          name: unifi
          ports:
            - containerPort: 8433
              name: https
            - containerPort: 8080
              name: http
            - containerPort: 3478
              name: stun
              protocol: UDP
            - containerPort: 6789
              name: speedtest
            - containerPort: 10001
              name: ubnt-discovery
              protocol: UDP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: unifi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: unifi
  name: unifi-tcp
  namespace: unifi
spec:
  loadBalancerIP: 192.168.1.250
  ports:
    - name: uap-inform
      port: 8080
    - name: controller-gui-api
      port: 8443
    - name: http-redirect
      port: 8880
    - name: https-redirect
      port: 8843
    - name: throughput-measurement
      port: 6789
    - name: wireless-client-redirector-port1
      port: 8881
    - name: wireless-client-redirector-port2
      port: 8882
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: unifi
  name: unifi-udp
  namespace: unifi
spec:
  loadBalancerIP: 192.168.1.250
  ports:
    - name: stun-port
      port: 3478
      protocol: UDP
    - name: ap-discovery
      port: 10001
      protocol: UDP
  type: LoadBalancer
